### PR TITLE
Bump to version v0.18.0

### PR DESCRIPTION
**Pull request by ecwyne**

### CODE REVIEW

**Comment by ecwyne** [comment]
I'd also be interested in helping keep this up to date on the [ramda org](https://atmospherejs.com/ramda) on atmosphere

**Comment by ccorcos** [comment]
Talk to @splendido  and get in on this issue ticket talking about it:

https://github.com/MeteorPackaging/ramda-wrapper/issues/1

I'm not so involved in this anymore now that I'm just using webpack:webpack

**Comment by splendido** [comment]
Sorry guys, I've been away for a while...
Just bumped to version 0.18.0.

**Comment by splendido** [comment]
@ecwyne I can add you to the package's maintainer if you're still willing to help keeping this up to date.
Just let me know!

**Comment by ecwyne** [comment]
@splendido I'd love to help keep it up to date! I'm using ramdajs on a daily basis now!

**Pull request closed without merging**
